# Python package
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

jobs:

- job: 'OSXBuild'
  pool:
    vmImage: 'macOS-10.13'


  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.5'
      architecture: 'x64'

  - script: |
      python -m pip install --upgrade pip 
      pip3 install pyinstaller
      pip3 install markdown
      pip3 install pyobjc
      pip3 install dmgbuild
    displayName: 'Install dependencies'

  - script: |
      python -m markdown README.md > README.html
      pyinstaller bundle/EntranceRandomizer.spec
      dmgbuild -s bundle/dmgsettings.py -D app=dist/EntranceRandomizer.app "AlttPEntranceRandomizer" dist/EntranceRandomizer_$(date '+%Y-%m-%d_%H_%M').dmg
    displayName: 'Build'
  - task: PublishBuildArtifacts@1
    displayName: 'Publish artifact: dist'
    inputs:
      pathtoPublish: 'dist'
      artifactName: 'dist'

